-- 001_core_schema.sql — Phase 0 core POS schema
--
-- Numbered SQL migration, applied in order by `make db-template`. No
-- down-migrations; the database is always droppable (ADR-0004).
--
-- Conventions a reader should know before going further:
--
--   * Primary keys are named <singular>_id, never `id`, and every foreign key
--     carries the identical name. That makes `JOIN products USING (product_id)`
--     legal throughout and makes `p.id = s.product_id` inversions impossible.
--     It is the cheapest text-to-SQL accuracy lever available (ADR-0001).
--
--   * Analytical queries filter on `business_date` (the store's trading day),
--     never on `sold_at`. Both are stored. This removes an entire class of
--     timezone silent-wrongs, which is threshold 1 in ADR-0001.
--
--   * Temporal tables use half-open date intervals [effective_from,
--     effective_to). `effective_to IS NULL` means "in force". A generated
--     `valid_period daterange` column carries those semantics natively, so a
--     query says `valid_period @> DATE '...'` and cannot get the boundary
--     wrong. Overlap is forbidden by an exclusion constraint; gaps are
--     permitted, because "no terms in force at that date" must be
--     distinguishable from "supplier not found" (see api/prompts/
--     retrieval_answer.md and corpus/README.md).
--
--   * Every table and column carries a COMMENT. `make schema-doc` generates
--     api/prompts/context/schema.md from them, so the schema documentation the
--     model reads cannot drift from the schema itself (ADR-0008).
--
--   * Money is numeric(12,2). Quantity is integer, signed — negative on
--     returns. There is no float anywhere in this schema.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ─────────────────────────────────────────────────────────────────────────────
-- Roles
--
-- Roles are cluster-wide, so they survive `DROP DATABASE` and must be created
-- idempotently. Passwords are set separately by `make db-roles` from .env —
-- this file stays credential-free.
--
-- pos_readonly is the role EVERY generated SQL query runs under (CLAUDE.md
-- rule 4). It provides read-only enforcement and a statement timeout. It does
-- NOT provide the row LIMIT: Postgres has no max-rows setting, so the LIMIT is
-- applied by the query wrapper in the API. See docs/PROGRESS.md.
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_app') THEN
        CREATE ROLE pos_app LOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pos_readonly') THEN
        CREATE ROLE pos_readonly LOGIN;
    END IF;
END
$$;

ALTER ROLE pos_readonly SET default_transaction_read_only = on;
ALTER ROLE pos_readonly SET statement_timeout = '5s';
ALTER ROLE pos_readonly SET idle_in_transaction_session_timeout = '10s';
ALTER ROLE pos_readonly SET search_path = public;
ALTER ROLE pos_app SET search_path = public;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO pos_app, pos_readonly;


-- ─────────────────────────────────────────────────────────────────────────────
-- Reference data
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE stores (
    store_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       text        NOT NULL UNIQUE,
    name       text        NOT NULL,
    city       text        NOT NULL,
    timezone   text        NOT NULL,
    opened_on  date        NOT NULL
);

COMMENT ON TABLE stores IS
    'Physical retail locations. The multi-store user interface is deferred '
    '(docs/PLAN.md cut list) but store_id is present on every store-scoped '
    'table from the start.';
COMMENT ON COLUMN stores.code IS 'Short human-readable store code, e.g. ST-01.';
COMMENT ON COLUMN stores.timezone IS
    'IANA timezone name. Determines the trading day (business_date) for sales '
    'rung up at this store.';

CREATE TABLE categories (
    category_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    department  text NOT NULL
);

COMMENT ON TABLE categories IS
    'Product categories, one level deep, grouped into departments. Demand '
    'seasonality and day-of-week patterns are properties of the category.';

CREATE TABLE suppliers (
    supplier_id   smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          text    NOT NULL UNIQUE,
    name          text    NOT NULL,
    contact_email text    NOT NULL,
    is_active     boolean NOT NULL DEFAULT true
);

COMMENT ON TABLE suppliers IS
    'Suppliers the business buys from. Chain-level, not store-scoped. '
    'Commercial terms and prices are NOT here — they are time-scoped and live '
    'in supplier_terms and supplier_prices.';

CREATE TABLE products (
    product_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku             text          NOT NULL UNIQUE,
    name            text          NOT NULL,
    category_id     smallint      NOT NULL REFERENCES categories (category_id),
    unit_of_measure text          NOT NULL,
    pack_size       int           NOT NULL DEFAULT 1,
    list_price      numeric(12,2) NOT NULL,
    is_active       boolean       NOT NULL DEFAULT true,
    discontinued_on date          NULL,
    CONSTRAINT products_list_price_positive CHECK (list_price > 0),
    CONSTRAINT products_pack_size_positive  CHECK (pack_size > 0)
);

COMMENT ON TABLE products IS
    'The product catalogue. Chain-wide: a product is the same product in every '
    'store. Per-store stock is in inventory; per-supplier cost is in '
    'supplier_prices.';
COMMENT ON COLUMN products.list_price IS
    'Shelf price (MRP) before any promotion, net of tax, in the currency on '
    'supplier_prices.currency. The price actually charged is on '
    'sale_lines.unit_price, which may be lower during a promotion.';

CREATE TABLE users (
    user_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     text     NOT NULL UNIQUE,
    display_name text     NOT NULL,
    role         text     NOT NULL
                          CHECK (role IN ('owner', 'manager', 'clerk')),
    store_id     smallint NULL REFERENCES stores (store_id),
    is_active    boolean  NOT NULL DEFAULT true
);

COMMENT ON TABLE users IS
    'Staff accounts and their roles. NOT readable by pos_readonly. Display '
    'names are role-and-ordinal labels ("Clerk 03"), never realistic person '
    'names — ADR-0002 forbids demoing with employee names, including '
    'synthetic ones, in a public repository.';
COMMENT ON COLUMN users.store_id IS
    'The store this user works at. NULL means chain-wide access. This is the '
    'entire data model for role-scoping: scoping is applied when the query is '
    'built, never by dropping rows from results afterwards (CLAUDE.md rule 5).';


-- ─────────────────────────────────────────────────────────────────────────────
-- Supplier relationships — temporal
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE supplier_products (
    supplier_product_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id  smallint NOT NULL REFERENCES suppliers (supplier_id),
    product_id   int      NOT NULL REFERENCES products (product_id),
    supplier_sku text     NOT NULL,
    is_preferred boolean  NOT NULL DEFAULT false,
    min_order_qty int     NOT NULL DEFAULT 1,
    case_pack     int     NOT NULL DEFAULT 1,
    UNIQUE (supplier_id, product_id),
    CONSTRAINT supplier_products_case_pack_positive CHECK (case_pack > 0)
);

COMMENT ON TABLE supplier_products IS
    'Which suppliers can supply which products, and the non-temporal facts '
    'about that relationship. Price is time-scoped and lives in '
    'supplier_prices.';
COMMENT ON COLUMN supplier_products.is_preferred IS
    'Exactly one supplier per product is preferred. Restock proposals default '
    'to the preferred supplier.';

CREATE TABLE supplier_prices (
    supplier_price_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id    smallint      NOT NULL REFERENCES suppliers (supplier_id),
    product_id     int           NOT NULL REFERENCES products (product_id),
    unit_cost      numeric(12,2) NOT NULL,
    currency       char(3)       NOT NULL,
    effective_from date          NOT NULL,
    effective_to   date          NULL,
    valid_period   daterange     GENERATED ALWAYS AS
                       (daterange(effective_from, effective_to)) STORED,
    source         text          NOT NULL DEFAULT 'seed'
                                 CHECK (source IN ('seed', 'document', 'manual')),
    supersedes_id  int           NULL REFERENCES supplier_prices (supplier_price_id),
    CONSTRAINT supplier_prices_cost_positive CHECK (unit_cost > 0),
    CONSTRAINT supplier_prices_interval_sane
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT supplier_prices_no_overlap
        EXCLUDE USING gist (supplier_id WITH =, product_id WITH =,
                            valid_period WITH &&)
);

COMMENT ON TABLE supplier_prices IS
    'What a supplier charges for a product, over time. One row per price '
    'period. A purchase order proposal records the supplier_price_id it was '
    'drafted against, so it can refuse to execute if a newer price now '
    'applies.';
COMMENT ON COLUMN supplier_prices.valid_period IS
    'Generated half-open range [effective_from, effective_to). Prefer '
    'valid_period @> DATE ''YYYY-MM-DD'' over comparing the two date columns '
    'by hand — it cannot get the boundary wrong. NULL effective_to is '
    'unbounded, so the current price matches any future date.';
COMMENT ON COLUMN supplier_prices.source IS
    'Where this row came from. ''seed'' is generated data; ''document'' is '
    'extracted from a real source document in Phase 2.';

CREATE TABLE supplier_terms (
    supplier_terms_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         smallint      NOT NULL REFERENCES suppliers (supplier_id),
    payment_terms_days  int           NOT NULL,
    lead_time_days      int           NOT NULL,
    min_order_value     numeric(12,2) NOT NULL,
    volume_discount_pct numeric(5,2)  NOT NULL DEFAULT 0,
    returns_window_days int           NOT NULL,
    effective_from      date          NOT NULL,
    effective_to        date          NULL,
    valid_period        daterange     GENERATED ALWAYS AS
                            (daterange(effective_from, effective_to)) STORED,
    source              text          NOT NULL DEFAULT 'seed'
                                      CHECK (source IN ('seed', 'document', 'manual')),
    source_note         text          NULL,
    supersedes_id       int           NULL REFERENCES supplier_terms (supplier_terms_id),
    CONSTRAINT supplier_terms_lead_time_sane CHECK (lead_time_days BETWEEN 0 AND 120),
    CONSTRAINT supplier_terms_interval_sane
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT supplier_terms_no_overlap
        EXCLUDE USING gist (supplier_id WITH =, valid_period WITH &&)
);

COMMENT ON TABLE supplier_terms IS
    'Commercial terms agreed with a supplier, over time. One row per term '
    'period; a renegotiation closes the old row and opens a new one. The '
    'exclusion constraint makes overlapping terms impossible, so "what are '
    'the terms on date D" always has at most one answer. Gaps ARE allowed: a '
    'date with no row means no terms were in force, which is different from '
    'the supplier not existing. Phase 2 populates history and provenance from '
    'real documents; it does not reshape this table.';
COMMENT ON COLUMN supplier_terms.payment_terms_days IS
    'Days to pay. 30 means Net 30.';
COMMENT ON COLUMN supplier_terms.lead_time_days IS
    'Contracted days between placing an order and delivery. Actual delivery '
    'performance is observable from purchase_orders.ordered_on vs received_on '
    'and is not always the same thing.';
COMMENT ON COLUMN supplier_terms.supersedes_id IS
    'The term period this one replaced. Mirrors the supersedes column in '
    'corpus/MANIFEST.csv so the database and the document corpus encode '
    'version chains the same way.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Promotions
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE promotions (
    promotion_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id     smallint     NOT NULL REFERENCES stores (store_id),
    name         text         NOT NULL,
    discount_pct numeric(5,2) NOT NULL,
    starts_on    date         NOT NULL,
    ends_on      date         NOT NULL,
    CONSTRAINT promotions_discount_range CHECK (discount_pct > 0 AND discount_pct < 90),
    CONSTRAINT promotions_dates_sane      CHECK (ends_on >= starts_on)
);

COMMENT ON TABLE promotions IS
    'Promotional events. Promotions are a real table rather than an invisible '
    'multiplier in the seed generator, so unexplained demand spikes are '
    'always explainable by a query. Date range is inclusive on both ends.';

CREATE TABLE promotion_products (
    promotion_id int NOT NULL REFERENCES promotions (promotion_id),
    product_id   int NOT NULL REFERENCES products (product_id),
    PRIMARY KEY (promotion_id, product_id)
);

COMMENT ON TABLE promotion_products IS 'Which products a promotion applies to.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Inventory
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE inventory (
    store_id        smallint NOT NULL REFERENCES stores (store_id),
    product_id      int      NOT NULL REFERENCES products (product_id),
    on_hand         int      NOT NULL,
    reorder_point   int      NOT NULL,
    reorder_qty     int      NOT NULL,
    last_counted_on date     NOT NULL,
    PRIMARY KEY (store_id, product_id),
    CONSTRAINT inventory_on_hand_non_negative     CHECK (on_hand >= 0),
    CONSTRAINT inventory_reorder_point_sane       CHECK (reorder_point >= 0),
    CONSTRAINT inventory_reorder_qty_positive     CHECK (reorder_qty > 0)
);

COMMENT ON TABLE inventory IS
    'Current stock per store per product, with that store''s restock policy. '
    'on_hand is a materialisation of the movement history: it equals the sum '
    'of inventory_movements.quantity minus the sum of sale_lines.quantity for '
    'the same store and product. That invariant is asserted by a test.';
COMMENT ON COLUMN inventory.reorder_point IS
    'Restock when on_hand falls to or below this. Set per store, because a '
    'busy store needs a higher floor than a quiet one. "What should we '
    'reorder" means on_hand <= reorder_point unless the question names an '
    'explicit number.';
COMMENT ON COLUMN inventory.reorder_qty IS
    'How many units to order when restocking, before rounding up to the '
    'supplier''s case pack and minimum order quantity.';

CREATE TABLE inventory_movements (
    movement_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       smallint NOT NULL REFERENCES stores (store_id),
    product_id     int      NOT NULL REFERENCES products (product_id),
    business_date  date     NOT NULL,
    movement_type  text     NOT NULL CHECK (movement_type IN
                       ('delivery', 'adjustment', 'shrinkage',
                        'return_to_supplier', 'count_correction')),
    quantity       int      NOT NULL,
    reference_type text     NULL CHECK (reference_type IN ('purchase_order')),
    reference_id   bigint   NULL,
    note           text     NULL,
    CONSTRAINT inventory_movements_quantity_nonzero CHECK (quantity <> 0)
);

COMMENT ON TABLE inventory_movements IS
    'Stock movements that are NOT sales: deliveries in, shrinkage out, '
    'stock-count corrections. Sales are already recorded in sale_lines and '
    'are deliberately not duplicated here — doing so would triple the largest '
    'table in the database for no new information. To reconstruct stock '
    'history you need both this table and sale_lines.';
COMMENT ON COLUMN inventory_movements.quantity IS
    'Signed. Positive increases stock (a delivery), negative decreases it '
    '(shrinkage, a return to the supplier).';
COMMENT ON COLUMN inventory_movements.reference_id IS
    'Loose reference to the row named by reference_type — a po_id when '
    'reference_type is ''purchase_order''. Not a foreign key, because the '
    'referent varies.';

CREATE TABLE stockout_days (
    store_id      smallint NOT NULL REFERENCES stores (store_id),
    product_id    int      NOT NULL REFERENCES products (product_id),
    business_date date     NOT NULL,
    PRIMARY KEY (store_id, product_id, business_date)
);

COMMENT ON TABLE stockout_days IS
    'Days a product was out of stock at a store while customers were still '
    'asking for it. This exists to prevent a specific analytical trap: sales '
    'are capped by available stock, so the products that stock out — exactly '
    'the products a restock question is about — have UNDERSTATED sales '
    'velocity. Velocity should be measured over days the product was '
    'actually available, which is what v_product_velocity_30d does.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Purchasing
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE purchase_orders (
    po_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id    smallint      NOT NULL REFERENCES stores (store_id),
    supplier_id smallint      NOT NULL REFERENCES suppliers (supplier_id),
    status      text          NOT NULL CHECK (status IN
                    ('draft', 'submitted', 'received', 'cancelled')),
    source      text          NOT NULL CHECK (source IN ('seed', 'agent', 'manual')),
    ordered_on  date          NOT NULL,
    expected_on date          NOT NULL,
    received_on date          NULL,
    subtotal    numeric(12,2) NOT NULL,
    created_by_user_id int    NULL REFERENCES users (user_id),
    CONSTRAINT purchase_orders_expected_after_ordered CHECK (expected_on >= ordered_on),
    CONSTRAINT purchase_orders_received_when_status
        CHECK ((status = 'received') = (received_on IS NOT NULL))
);

COMMENT ON TABLE purchase_orders IS
    'Orders placed with suppliers. Seeded history exists so that supplier '
    'delivery performance is observable — comparing ordered_on to received_on '
    'against the contracted supplier_terms.lead_time_days is a real question '
    'with a real answer. From Phase 4 the procurement agent writes rows here '
    'with source = ''agent'', but only after a human approves.';
COMMENT ON COLUMN purchase_orders.source IS
    'Who created this order: ''seed'' is generated history, ''agent'' was '
    'drafted by the procurement agent and approved by a human, ''manual'' was '
    'entered by hand.';
COMMENT ON COLUMN purchase_orders.expected_on IS
    'Delivery date recorded against this order. received_on is when it actually '
    'arrived. NOT a substitute for the contracted lead time: every order in this '
    'dataset carries expected_on = ordered_on + the supplier''s CURRENT '
    'lead_time_days, including the 7,905 orders placed before that supplier '
    'renegotiated, so for 5,329 of 15,723 orders it does not match the '
    'supplier_terms row in force on ordered_on. A question about the lead time a '
    'supplier CONTRACTED to must read supplier_terms.lead_time_days with '
    'valid_period @> ordered_on; expected_on answers a different question.';

CREATE TABLE purchase_order_lines (
    po_line_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id             bigint        NOT NULL REFERENCES purchase_orders (po_id),
    product_id        int           NOT NULL REFERENCES products (product_id),
    quantity_ordered  int           NOT NULL,
    quantity_received int           NOT NULL DEFAULT 0,
    unit_cost         numeric(12,2) NOT NULL,
    line_total        numeric(12,2) NOT NULL,
    CONSTRAINT po_lines_quantity_ordered_positive CHECK (quantity_ordered > 0),
    CONSTRAINT po_lines_received_not_negative     CHECK (quantity_received >= 0)
);

COMMENT ON TABLE purchase_order_lines IS
    'Line items on a purchase order. quantity_received may be less than '
    'quantity_ordered on a short delivery.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Sales
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE sales (
    sale_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       smallint      NOT NULL REFERENCES stores (store_id),
    sold_at        timestamptz   NOT NULL,
    business_date  date          NOT NULL,
    sale_type      text          NOT NULL CHECK (sale_type IN ('sale', 'return')),
    tender_type    text          NOT NULL CHECK (tender_type IN
                       ('card', 'cash', 'mobile', 'voucher')),
    subtotal       numeric(12,2) NOT NULL,
    discount_total numeric(12,2) NOT NULL,
    tax_total      numeric(12,2) NOT NULL,
    total          numeric(12,2) NOT NULL,
    -- Target for the composite foreign key from sale_lines. Redundant with the
    -- primary key, and deliberately so: it is what lets Postgres guarantee the
    -- denormalised store_id and business_date on sale_lines can never drift.
    UNIQUE (sale_id, store_id, business_date)
);

COMMENT ON TABLE sales IS
    'Transaction headers — one row per basket. A refund is a separate row with '
    'sale_type = ''return'' and negative quantities on its lines. Who rang the '
    'sale up is deliberately NOT in this table; see sale_operators.';
COMMENT ON COLUMN sales.sold_at IS
    'Exact transaction time, with timezone. Use this only when the time of day '
    'matters. For anything aggregated by day, use business_date.';
COMMENT ON COLUMN sales.business_date IS
    'The store''s trading day in its own timezone. This is the correct column '
    'for every daily, weekly, monthly or year-on-year aggregation. It is not '
    'always equal to the UTC date of sold_at.';
COMMENT ON COLUMN sales.subtotal IS
    'Sum of the line totals, NET of tax. Equals sum(sale_lines.line_total) for '
    'this sale.';
COMMENT ON COLUMN sales.discount_total IS
    'Total promotional discount given on this sale, as a positive number. It '
    'has already been taken off subtotal — do not subtract it again.';
COMMENT ON COLUMN sales.tax_total IS
    'GST charged, summed per line at the rate that applied to that product''s '
    'category ON THAT DAY. Rates vary by category AND over time — they were '
    'restructured on 22 September 2025, inside this sales history. See the '
    'gst_rates table. Two consequences: the effective rate on a basket is a '
    'blend and cannot be assumed, and the rate on an old sale is not the rate '
    'today.';
COMMENT ON COLUMN sales.total IS
    'What the customer paid: subtotal + tax_total. Revenue questions normally '
    'mean subtotal (net of tax); cash-collected questions mean total.';

CREATE TABLE sale_lines (
    sale_line_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id         bigint        NOT NULL,
    store_id        smallint      NOT NULL,
    business_date   date          NOT NULL,
    product_id      int           NOT NULL REFERENCES products (product_id),
    promotion_id    int           NULL REFERENCES promotions (promotion_id),
    quantity        int           NOT NULL,
    unit_price      numeric(12,2) NOT NULL,
    unit_cost       numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) NOT NULL,
    line_total      numeric(12,2) NOT NULL,
    CONSTRAINT sale_lines_quantity_nonzero CHECK (quantity <> 0),
    FOREIGN KEY (sale_id, store_id, business_date)
        REFERENCES sales (sale_id, store_id, business_date)
);

COMMENT ON TABLE sale_lines IS
    'Line items. store_id and business_date are copied down from the sales '
    'header so that sales-velocity queries never need to join it; the '
    'three-column foreign key makes it impossible for those copies to '
    'disagree with the header.';
COMMENT ON COLUMN sale_lines.quantity IS
    'Signed: positive on a sale, NEGATIVE on a return. So SUM(quantity) is NET '
    'units, not gross units sold. If you want gross, filter to quantity > 0 — '
    'or use daily_product_sales, which names units_sold, return_units and '
    'net_units separately.';
COMMENT ON COLUMN sale_lines.unit_price IS
    'Price actually charged per unit, after any promotional discount. Compare '
    'against products.list_price to see the discount.';
COMMENT ON COLUMN sale_lines.unit_cost IS
    'What this unit cost the business, frozen at the time of sale. Margin is '
    'line_total minus quantity * unit_cost. Do not join to supplier_prices for '
    'historical margin — that gives today''s cost, not the cost then.';

CREATE TABLE sale_operators (
    sale_id       bigint   PRIMARY KEY,
    store_id      smallint NOT NULL,
    business_date date     NOT NULL,
    user_id       int      NOT NULL REFERENCES users (user_id),
    FOREIGN KEY (sale_id, store_id, business_date)
        REFERENCES sales (sale_id, store_id, business_date)
);

COMMENT ON TABLE sale_operators IS
    'Which member of staff rang up which sale. Separated from the sales table '
    'and NOT granted to pos_readonly, so the natural-language query interface '
    'is structurally incapable of returning who did what. ADR-0002 requires '
    'that the agent reports patterns, never people; keeping this out of reach '
    'makes that a property of the schema rather than a rule a prompt is '
    'trusted to follow. Pattern-level analysis runs as pos_app.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes
-- ─────────────────────────────────────────────────────────────────────────────

CREATE INDEX sale_lines_velocity_idx  ON sale_lines (store_id, product_id, business_date);
CREATE INDEX sale_lines_date_idx      ON sale_lines (business_date, store_id);
CREATE INDEX sale_lines_sale_idx      ON sale_lines (sale_id);
CREATE INDEX sale_lines_product_idx   ON sale_lines (product_id);
CREATE INDEX sale_lines_promotion_idx ON sale_lines (promotion_id)
    WHERE promotion_id IS NOT NULL;

CREATE INDEX sales_store_date_idx ON sales (store_id, business_date);
CREATE INDEX sales_sold_at_idx    ON sales (sold_at);

CREATE INDEX sale_operators_user_idx ON sale_operators (user_id, business_date);

CREATE INDEX inventory_below_reorder_idx ON inventory (store_id)
    WHERE on_hand <= reorder_point;
CREATE INDEX inventory_product_idx ON inventory (product_id);

CREATE INDEX inventory_movements_lookup_idx
    ON inventory_movements (store_id, product_id, business_date);
CREATE INDEX inventory_movements_date_idx ON inventory_movements (business_date);

CREATE INDEX purchase_orders_store_status_idx
    ON purchase_orders (store_id, status, expected_on);
CREATE INDEX purchase_orders_supplier_idx ON purchase_orders (supplier_id, ordered_on);
CREATE INDEX purchase_order_lines_po_idx      ON purchase_order_lines (po_id);
CREATE INDEX purchase_order_lines_product_idx ON purchase_order_lines (product_id);

CREATE INDEX products_category_idx        ON products (category_id);
CREATE INDEX supplier_products_product_idx ON supplier_products (product_id);
CREATE INDEX supplier_prices_product_idx   ON supplier_prices (product_id);
CREATE INDEX promotions_store_dates_idx    ON promotions (store_id, starts_on, ends_on);
CREATE INDEX promotion_products_product_idx ON promotion_products (product_id);
CREATE INDEX users_store_idx ON users (store_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- Derived objects
--
-- daily_product_sales is a materialised view rather than a seeded table so it
-- can never disagree with sale_lines. `make seed` refreshes it after loading.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE MATERIALIZED VIEW daily_product_sales AS
SELECT
    sl.store_id,
    sl.product_id,
    sl.business_date,
    COALESCE(sum(sl.quantity)  FILTER (WHERE sl.quantity > 0), 0)  AS units_sold,
    COALESCE(-sum(sl.quantity) FILTER (WHERE sl.quantity < 0), 0)  AS return_units,
    sum(sl.quantity)                                               AS net_units,
    sum(sl.line_total)                                             AS net_revenue,
    sum(sl.quantity * sl.unit_cost)                                AS cogs
FROM sale_lines sl
GROUP BY sl.store_id, sl.product_id, sl.business_date;

COMMENT ON MATERIALIZED VIEW daily_product_sales IS
    'Per store, per product, per trading day sales rollup, derived from '
    'sale_lines. Refreshed by `make seed`. Gross, returns and net are named '
    'separately so no query has to remember that sale_lines.quantity is '
    'signed. Days with no sales have no row.';

COMMENT ON COLUMN daily_product_sales.units_sold IS
    'Units sold outward on this day. Positive quantities only — returns are '
    'excluded and counted separately. This is GROSS units.';
COMMENT ON COLUMN daily_product_sales.return_units IS
    'Units handed back on this day, as a POSITIVE number.';
COMMENT ON COLUMN daily_product_sales.net_units IS
    'units_sold minus return_units. This is the honest "how many did we move" '
    'figure and the right default for a sales-volume question.';
COMMENT ON COLUMN daily_product_sales.net_revenue IS
    'Takings for the day, NET of returns and NET of GST. Refund lines carry a '
    'negative line_total and are already subtracted. Add sales.tax_total if a '
    'question is about cash collected rather than revenue.';
COMMENT ON COLUMN daily_product_sales.cogs IS
    'Cost of goods sold, net of returns, using the cost frozen on each line at '
    'the time of sale. Margin for a period is net_revenue - cogs.';

CREATE UNIQUE INDEX daily_product_sales_pk_idx
    ON daily_product_sales (store_id, product_id, business_date);
CREATE INDEX daily_product_sales_date_idx ON daily_product_sales (business_date);

-- Trailing-30-day sales velocity.
--
-- The window is anchored on the latest trading day present in the data, NOT on
-- current_date. The seed has a fixed end date so it can be byte-identical on
-- re-run; a current_date-anchored view would return nothing the moment
-- wall-clock passed that date. Self-anchoring means this works on any day.
CREATE VIEW v_product_velocity_30d AS
WITH anchor AS (
    SELECT max(business_date) AS as_of_date FROM daily_product_sales
),
bounds AS (
    SELECT as_of_date, as_of_date - 29 AS from_date FROM anchor
),
sold AS (
    SELECT d.store_id, d.product_id,
           sum(d.net_units)     AS net_units_30d,
           sum(d.units_sold)    AS units_sold_30d,
           sum(d.net_revenue) AS revenue_30d
    FROM daily_product_sales d, bounds b
    WHERE d.business_date BETWEEN b.from_date AND b.as_of_date
    GROUP BY d.store_id, d.product_id
),
outages AS (
    SELECT s.store_id, s.product_id, count(*) AS stockout_days_30d
    FROM stockout_days s, bounds b
    WHERE s.business_date BETWEEN b.from_date AND b.as_of_date
    GROUP BY s.store_id, s.product_id
)
SELECT
    i.store_id,
    i.product_id,
    b.as_of_date,
    COALESCE(sold.units_sold_30d, 0)     AS units_sold_30d,
    COALESCE(sold.net_units_30d, 0)      AS net_units_30d,
    COALESCE(sold.revenue_30d, 0)::numeric(12,2) AS revenue_30d,
    COALESCE(o.stockout_days_30d, 0)     AS stockout_days_30d,
    30 - COALESCE(o.stockout_days_30d, 0) AS available_days_30d,
    round(COALESCE(sold.net_units_30d, 0)::numeric
          / GREATEST(30 - COALESCE(o.stockout_days_30d, 0), 1), 3) AS units_per_day
FROM inventory i
CROSS JOIN bounds b
LEFT JOIN sold    ON sold.store_id = i.store_id AND sold.product_id = i.product_id
LEFT JOIN outages o ON o.store_id  = i.store_id AND o.product_id   = i.product_id;

COMMENT ON VIEW v_product_velocity_30d IS
    'How fast each product sells at each store, over the 30 trading days '
    'ending on the most recent day present in the data. units_per_day divides '
    'by the days the product was actually AVAILABLE, not by 30, so a product '
    'that stocked out is not penalised for the days it could not be sold. One '
    'row per row of inventory, including products that sold nothing.';

CREATE VIEW v_supplier_terms_current AS
SELECT supplier_terms_id, supplier_id, payment_terms_days, lead_time_days,
       min_order_value, volume_discount_pct, returns_window_days,
       effective_from, source
FROM supplier_terms
WHERE effective_to IS NULL;

COMMENT ON VIEW v_supplier_terms_current IS
    'The supplier terms in force now — the rows with no end date. For terms as '
    'they stood on some past date, query supplier_terms with '
    'valid_period @> DATE ''YYYY-MM-DD'' instead. A supplier missing from this '
    'view has no terms currently in force, which is not the same as having no '
    'terms on record.';

CREATE VIEW v_supplier_price_current AS
SELECT supplier_price_id, supplier_id, product_id, unit_cost, currency,
       effective_from, source
FROM supplier_prices
WHERE effective_to IS NULL;

COMMENT ON VIEW v_supplier_price_current IS
    'The price each supplier currently charges for each product. For a price '
    'on a past date, query supplier_prices with valid_period @> DATE.';

CREATE VIEW v_stock_status AS
SELECT
    i.store_id,
    i.product_id,
    p.sku,
    p.name                AS product_name,
    c.name                AS category_name,
    c.department,
    i.on_hand,
    i.reorder_point,
    i.reorder_qty,
    (i.on_hand <= i.reorder_point) AS below_reorder_point,
    v.units_per_day,
    v.net_units_30d,
    v.stockout_days_30d,
    CASE WHEN v.units_per_day > 0
         THEN round(i.on_hand::numeric / v.units_per_day, 1)
    END                   AS days_of_cover,
    sp.supplier_id        AS preferred_supplier_id,
    s.name                AS preferred_supplier_name,
    t.lead_time_days,
    t.payment_terms_days,
    cp.unit_cost          AS current_unit_cost,
    sp.case_pack,
    sp.min_order_qty,
    COALESCE(oo.on_order_qty, 0) AS on_order_qty
FROM inventory i
JOIN products   p USING (product_id)
JOIN categories c USING (category_id)
LEFT JOIN v_product_velocity_30d v
       ON v.store_id = i.store_id AND v.product_id = i.product_id
LEFT JOIN supplier_products sp
       ON sp.product_id = i.product_id AND sp.is_preferred
LEFT JOIN suppliers s ON s.supplier_id = sp.supplier_id
LEFT JOIN v_supplier_terms_current t ON t.supplier_id = sp.supplier_id
LEFT JOIN v_supplier_price_current cp
       ON cp.supplier_id = sp.supplier_id AND cp.product_id = i.product_id
LEFT JOIN (
    SELECT po.store_id, pol.product_id,
           sum(pol.quantity_ordered - pol.quantity_received) AS on_order_qty
    FROM purchase_order_lines pol
    JOIN purchase_orders po USING (po_id)
    WHERE po.status IN ('draft', 'submitted')
    GROUP BY po.store_id, pol.product_id
) oo ON oo.store_id = i.store_id AND oo.product_id = i.product_id;

COMMENT ON VIEW v_stock_status IS
    'One row per store per product: what is on the shelf, how fast it moves, '
    'how long the shelf will last, who supplies it and on what terms, and how '
    'much is already on order. days_of_cover is on_hand divided by daily '
    'velocity — low days_of_cover means running out soon. NULL days_of_cover '
    'means the product has not sold in the last 30 days, which is different '
    'from running out fast.';


-- ─────────────────────────────────────────────────────────────────────────────
-- Grants
--
-- pos_readonly is granted SELECT on business data only. It is NOT granted
-- users (staff identities) or sale_operators (who rang up which sale) —
-- see ADR-0002.
-- ─────────────────────────────────────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_app;

GRANT SELECT ON
    stores, categories, suppliers, products,
    supplier_products, supplier_prices, supplier_terms,
    promotions, promotion_products,
    inventory, inventory_movements, stockout_days,
    purchase_orders, purchase_order_lines,
    sales, sale_lines,
    daily_product_sales,
    v_product_velocity_30d, v_supplier_terms_current,
    v_supplier_price_current, v_stock_status
TO pos_readonly;

COMMIT;
