-- 002_gst_rates.sql — GST as a temporal record
--
-- India restructured GST with effect from 22 September 2025: the 56th GST
-- Council meeting (3 September 2025) removed the 12% and 28% slabs. Twelve
-- percent items moved almost entirely to 5%, around 90% of 28% items moved to
-- 18%, and luxury and sin goods — aerated beverages among them — moved to a
-- new 40% slab. The structure went from 0/5/12/18/28 to 0/5/18/40.
--
-- That date falls INSIDE the seeded window, so the rate is not a property of a
-- category. It is a property of a category on a date, and this table says so.
--
-- Two reasons it is worth its own table rather than a column on categories:
--
--   1. It puts the project's temporal thesis in the structured layer as well
--      as the document layer, and under an identical query pattern. A question
--      about a supplier's terms in March and a question about the tax rate in
--      March are answered the same way — `valid_period @> DATE '...'`. One
--      idea to learn, two places it applies.
--
--   2. It creates a real silent-wrong trap rather than an invented one.
--      "What was our average tax rate last year" over a period spanning
--      22 September returns a blend that was true of no actual period. It
--      executes cleanly, returns a plausible number, and is wrong. That is
--      ADR-0001's first threshold, and this one was found in the domain
--      rather than constructed for the eval set.
--
-- Same machinery as supplier_terms: half-open [from, to), NULL meaning in
-- force, a generated daterange, and a gist exclusion constraint so a category
-- can never have two rates on one day.

BEGIN;

CREATE TABLE gst_rates (
    gst_rate_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    smallint     NOT NULL REFERENCES categories (category_id),
    rate_pct       numeric(5,2) NOT NULL,
    effective_from date         NOT NULL,
    effective_to   date         NULL,
    valid_period   daterange    GENERATED ALWAYS AS
                       (daterange(effective_from, effective_to)) STORED,
    source         text         NOT NULL DEFAULT 'seed'
                                CHECK (source IN ('seed', 'document', 'manual')),
    notes          text         NULL,
    supersedes_id  int          NULL REFERENCES gst_rates (gst_rate_id),
    CONSTRAINT gst_rates_rate_range CHECK (rate_pct >= 0 AND rate_pct <= 100),
    CONSTRAINT gst_rates_interval_sane
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT gst_rates_no_overlap
        EXCLUDE USING gist (category_id WITH =, valid_period WITH &&)
);

COMMENT ON TABLE gst_rates IS
    'The GST rate for each category, over time. One row per rate period. The '
    'rate India charges on a product changed on 22 September 2025 (56th GST '
    'Council): the 12% and 28% slabs were withdrawn, most 12% items moved to '
    '5%, most 28% items to 18%, and aerated beverages to a new 40% slab. That '
    'date is inside the sales history, so ANY question about tax over a period '
    'crossing it has two answers, not one. Averaging across the boundary '
    'produces a number that was never the rate.';
COMMENT ON COLUMN gst_rates.rate_pct IS
    'Percentage points, not a fraction: 18 means 18%%, not 1800%%. Divide by '
    '100 before multiplying a value by it.';
COMMENT ON COLUMN gst_rates.valid_period IS
    'Generated half-open range [effective_from, effective_to). Use '
    'valid_period @> <the sale''s business_date> to get the rate that actually '
    'applied to a sale. Comparing the two date columns by hand risks an '
    'off-by-one on 22 September 2025 itself.';
COMMENT ON COLUMN gst_rates.effective_to IS
    'NULL means in force. Every category has exactly one open-ended row.';
COMMENT ON COLUMN gst_rates.notes IS
    'What changed and why. Populated for the reform rows.';

CREATE VIEW v_gst_rate_current AS
SELECT gst_rate_id, category_id, rate_pct, effective_from, notes
FROM gst_rates
WHERE effective_to IS NULL;

COMMENT ON VIEW v_gst_rate_current IS
    'The GST rate in force now, per category. Correct for a question about '
    'today. WRONG for any question about a past period — historical tax must '
    'come from gst_rates with valid_period @> the business_date of the sale, '
    'because rates changed on 22 September 2025.';

GRANT SELECT, INSERT, UPDATE, DELETE ON gst_rates TO pos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_app;
GRANT SELECT ON gst_rates, v_gst_rate_current TO pos_readonly;

COMMIT;
