-- 003_festivals.sql — the festival calendar as data
--
-- Festivals were a multiplier inside the seed generator and nowhere in the
-- database. Promotions are a real table precisely so that demand spikes are
-- explainable by query; festivals cause much larger spikes than promotions do,
-- and were not explainable at all.
--
-- The gap showed up in a staged eval run. Asked to compare Holi 2026 with Holi
-- 2025, the model went looking for a *promotion* named Holi — a reasonable
-- guess, since that was the only thing in the schema resembling a named event —
-- and returned nothing. The window was not knowable from anything it had been
-- given.
--
-- The alternative was listing eighteen months of dates in
-- business_context.md. That would have the model hardcoding literals into
-- every query, and would leave "which festivals fell in Q3" permanently
-- unanswerable. This is the same call already made for promotions.
--
-- The generator already held every value here; this only exposes it.

BEGIN;

CREATE TABLE festivals (
    festival_id    smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text    NOT NULL,
    festival_date  date    NOT NULL,
    ramp_start     date    NOT NULL,
    ramp_end       date    NOT NULL,
    is_regional    boolean NOT NULL DEFAULT false,
    notes          text    NULL,
    UNIQUE (name, festival_date),
    CONSTRAINT festivals_window_contains_the_day
        CHECK (ramp_start <= festival_date AND festival_date <= ramp_end)
);

COMMENT ON TABLE festivals IS
    'The festival calendar for the trading window, one row per festival '
    'occurrence. Use this rather than hardcoding dates: it is what makes '
    '"how did we do over Diwali" and "which festivals fell in Q3" answerable '
    'by query. Only festivals whose day falls inside the sales history are '
    'listed.';
COMMENT ON COLUMN festivals.festival_date IS
    'The festival itself. Note this is usually NOT the busiest day — trade '
    'peaks in the run-up and often falls on the day, so a question about '
    'festival trade almost always means the window, not the date.';
COMMENT ON COLUMN festivals.ramp_start IS
    'First day demand starts building for this festival. For Dhanteras that is '
    'about four weeks out; for a minor festival, a few days.';
COMMENT ON COLUMN festivals.ramp_end IS
    'Last day still affected, including the post-festival slump. Use '
    'business_date BETWEEN ramp_start AND ramp_end for "during the festival".';
COMMENT ON COLUMN festivals.is_regional IS
    'True when the festival lands harder in some of our stores than others — '
    'Ganesh Chaturthi is far larger in Pune than in Nagpur. Comparing stores '
    'across a regional festival without normalising against each store''s own '
    'baseline measures store size, not the festival.';

CREATE INDEX festivals_date_idx ON festivals (festival_date);
CREATE INDEX festivals_window_idx ON festivals (ramp_start, ramp_end);

GRANT SELECT, INSERT, UPDATE, DELETE ON festivals TO pos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_app;
GRANT SELECT ON festivals TO pos_readonly;

COMMIT;
