-- 004_retrieval.sql — Phase 3 retrieval layer
--
-- Numbered SQL migration, applied in order (ADR-0004). No down-migrations.
--
-- Two tables and an extension, and the first table is the one Phase 2 argued
-- for and then proved:
--
--   * `supplier_term_clauses` records what a document SAYS, clause by clause.
--     `supplier_terms` stays exactly as it is — the wide, superseding,
--     text-to-SQL-friendly projection of what is IN FORCE. These answer
--     different questions and neither replaces the other.
--
--     Phase 2 turned this from a design argument into a measurement. The corpus
--     contains two clause-level amendments that vary three clauses and restate
--     nothing else. Extraction returned exactly those three, correctly. But the
--     gold set is derived from `supplier_terms`, whose row carries the full
--     INHERITED set, so every clause the amendment deliberately omits scored as
--     a miss — and what was being measured was the inheritance, not the
--     extraction. Both documents are excluded from the Phase 2 score with the
--     exclusion printed. This table is what un-excludes them.
--
--   * `doc_chunks` is the retrieval unit. Every chunk carries
--     `effective_from` / `effective_to` (CLAUDE.md rule 7) so a date filter can
--     be applied BEFORE the vector search rather than after it, and a half-open
--     `valid_period` for the same reason `supplier_terms` has one: a query says
--     `valid_period @> DATE '...'` and cannot get the boundary wrong.
--
-- Conventions from 001 that still apply: <singular>_id primary keys, half-open
-- date intervals, numeric money, a COMMENT on everything so `make schema-doc`
-- keeps api/prompts/context/schema.md from drifting.
--
-- ROLE SCOPE IS APPLIED BEFORE GENERATION, NEVER AFTER (rule 5). The columns
-- that make that possible live on the chunk, so the filter is part of the
-- retrieval query rather than a post-filter over its results.

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

-- ─────────────────────────────────────────────────────────────────────────────
-- Clause-level provenance
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE supplier_term_clauses (
    supplier_term_clause_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         int           NOT NULL REFERENCES suppliers (supplier_id),
    doc_id              text          NOT NULL,
    clause              text          NOT NULL,
    clause_number       text          NULL,
    value_numeric       numeric(12,2) NULL,
    value_text          text          NULL,
    verbatim            text          NOT NULL,
    effective_from      date          NOT NULL,
    effective_to        date          NULL,
    valid_period        daterange     GENERATED ALWAYS AS
                            (daterange(effective_from, effective_to)) STORED,
    source              text          NOT NULL DEFAULT 'extracted',

    CONSTRAINT supplier_term_clauses_period_sane
        CHECK (effective_to IS NULL OR effective_to > effective_from),

    -- Deliberately NOT an exclusion constraint on (supplier, clause, period).
    -- Two documents CAN state the same clause over overlapping periods — that
    -- is what a contradiction between a contract and a later amendment looks
    -- like, and `retrieval_answer.md` is written to surface exactly that
    -- ("If two retrieved documents disagree, say so and give both with their
    -- dates rather than silently picking one"). Forbidding it here would make
    -- the interesting case unrepresentable.
    CONSTRAINT supplier_term_clauses_one_value
        CHECK (value_numeric IS NOT NULL OR value_text IS NOT NULL)
);

CREATE INDEX supplier_term_clauses_lookup
    ON supplier_term_clauses (supplier_id, clause, effective_from DESC);
CREATE INDEX supplier_term_clauses_period
    ON supplier_term_clauses USING gist (valid_period);

COMMENT ON TABLE supplier_term_clauses IS
    'What a supplier document SAYS, one row per clause it states. Distinct from '
    'supplier_terms, which is the wide projection of what is IN FORCE. An '
    'amendment that varies three clauses produces three rows here and does not '
    'restate the rest; the set in force is computed from the whole chain. '
    'Populated by Phase 3 from corpus/extracted/.';
COMMENT ON COLUMN supplier_term_clauses.doc_id IS
    'The corpus document this clause was read from, matching MANIFEST.csv. This '
    'is the provenance: it answers "which document said so", which supplier_terms '
    'structurally cannot.';
COMMENT ON COLUMN supplier_term_clauses.clause IS
    'Clause name, matching the extraction schema: payment_terms_days, '
    'lead_time_days, min_order_value, volume_discount_pct, returns_window_days.';
COMMENT ON COLUMN supplier_term_clauses.clause_number IS
    'The number as printed in the document ("3", "7"). Text, not integer: '
    'amendments cite "3(b)" and a schema that assumed integers would lose it.';
COMMENT ON COLUMN supplier_term_clauses.verbatim IS
    'The sentence as it appears in the document. This is what makes a citation '
    'checkable by a reader rather than trusted.';
COMMENT ON COLUMN supplier_term_clauses.valid_period IS
    'Half-open [effective_from, effective_to). Query with valid_period @> DATE.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Retrieval chunks
--
-- 384 dimensions: bge-small-en-v1.5, which runs on CPU with no quota and no
-- rate limit (CLAUDE.md rule 2 — embeddings stay local at every tier). The
-- dimension is part of the column type, so changing embedding model is a
-- migration and not a silent behaviour change.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE doc_chunks (
    doc_chunk_id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id              text          NOT NULL,
    doc_type            text          NOT NULL,
    chunk_index         int           NOT NULL,
    content             text          NOT NULL,
    embedding           vector(384)   NULL,

    supplier_id         int           NULL REFERENCES suppliers (supplier_id),
    store_id            int           NULL REFERENCES stores (store_id),

    effective_from      date          NOT NULL,
    effective_to        date          NULL,
    valid_period        daterange     GENERATED ALWAYS AS
                            (daterange(effective_from, effective_to)) STORED,

    content_sha256      text          NOT NULL,

    CONSTRAINT doc_chunks_unique_position UNIQUE (doc_id, chunk_index),
    CONSTRAINT doc_chunks_period_sane
        CHECK (effective_to IS NULL OR effective_to > effective_from)
);

CREATE INDEX doc_chunks_period ON doc_chunks USING gist (valid_period);
CREATE INDEX doc_chunks_scope ON doc_chunks (supplier_id, store_id);

-- No ANN index. 40 documents is a few hundred chunks, where an exact scan is
-- both faster and exactly reproducible; an HNSW index would make recall depend
-- on build parameters and give this project a reproducibility claim it would
-- then have to qualify. Add one when the corpus makes it necessary, and record
-- what it costs in recall when you do.

COMMENT ON TABLE doc_chunks IS
    'Retrieval units from corpus/parsed/. Every chunk carries its own validity '
    'period so date filtering happens BEFORE the vector search, and scope '
    'columns so role restriction is part of the retrieval query rather than a '
    'filter over its results (CLAUDE.md rules 5 and 7).';
COMMENT ON COLUMN doc_chunks.embedding IS
    'bge-small-en-v1.5, 384d, CPU-local. NULL until make embed has run, which '
    'is why nothing may assume it is populated.';
COMMENT ON COLUMN doc_chunks.supplier_id IS
    'Scope column. NULL means the chunk is not supplier-specific — a policy '
    'applies chain-wide — and a scoped query must therefore match NULL as well '
    'as its own supplier, or it silently loses every policy document.';
COMMENT ON COLUMN doc_chunks.content_sha256 IS
    'SHA-256 of content. Lets a re-embed skip unchanged chunks, and makes '
    '"the parse moved underneath the embeddings" detectable rather than silent.';
COMMENT ON COLUMN doc_chunks.valid_period IS
    'Half-open [effective_from, effective_to). Query with valid_period @> DATE. '
    'A date with no chunk in force is "no document in force", which is NOT the '
    'same as "not found" — demo beat 2 rests on that distinction.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Grants
--
-- Both tables are business data and pos_readonly gets SELECT. Neither carries
-- staff identity, so ADR-0002's exclusion of users and sale_operators does not
-- extend here.
-- ─────────────────────────────────────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE, DELETE ON supplier_term_clauses, doc_chunks TO pos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_app;
GRANT SELECT ON supplier_term_clauses, doc_chunks TO pos_readonly;

COMMIT;
