-- 005_agent.sql — Phase 4 agent runs, proposals and audit
--
-- Numbered SQL migration, applied in order (ADR-0004). No down-migrations.
--
-- ADR-0003 chose to write the loop rather than adopt LangGraph, and the reason
-- lands here: **the agent is stateless and the database is the source of
-- truth.** Every claim Phase 4 has to make is a property of these tables, not of
-- the process:
--
--   "survives a server restart"   a row that is not `running` after a crash is
--                                 reclaimable, and nothing was held in memory
--   "expires"                     expires_at is a column, not a timer
--   "re-validates its inputs"     the inputs are recorded, so they can be
--                                 compared to the world at execution time
--   "full reasoning visible"      reasoning is a column on the proposal, not a
--                                 log line that scrolled away
--
-- **The audit log falls out of this rather than being written separately**
-- (ADR-0003, reason 3). `agent_events` is append-only and every state change
-- goes through it, so "what happened" is a query rather than a reconstruction.
--
-- ADR-0002's constraint holds here too: **the agent reports patterns, never
-- people.** Nothing in these tables references `sale_operators`, and the only
-- person recorded is the approver — which is the one identity the workflow is
-- actually about.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- Runs
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE agent_runs (
    agent_run_id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status          text        NOT NULL DEFAULT 'queued',
    prompt          text        NOT NULL,
    plan            text        NULL,

    -- Scope is recorded on the RUN, not re-derived per tool call. Rule 5 says
    -- the restriction is applied before generation; a run that carries its own
    -- scope cannot drift from it halfway through, and an agent acting for a
    -- store-scoped user is where rule 5 stops being about reading.
    requested_by    text        NOT NULL,
    role            text        NOT NULL,
    store_id        int         NULL REFERENCES stores (store_id),

    -- Rule 3: the loop caps at ~6 tool calls. Stored per run rather than read
    -- from config at execution time, so a run's budget is a fact about that run
    -- and a later config change cannot retroactively make it look compliant.
    max_tool_calls  int         NOT NULL DEFAULT 6,
    tool_calls_used int         NOT NULL DEFAULT 0,
    max_spend_usd   numeric(8,4) NOT NULL DEFAULT 0.50,
    spend_usd       numeric(8,4) NOT NULL DEFAULT 0,

    created_at      timestamptz NOT NULL DEFAULT now(),
    started_at      timestamptz NULL,
    finished_at     timestamptz NULL,
    -- The worker that claimed it. A row claimed by a worker that no longer
    -- exists is how "survived a restart" gets tested rather than asserted.
    claimed_by      text        NULL,
    claimed_at      timestamptz NULL,
    error           text        NULL,

    CONSTRAINT agent_runs_status_known CHECK (
        status IN ('queued', 'running', 'awaiting_approval', 'done', 'failed')
    ),
    CONSTRAINT agent_runs_within_call_budget
        CHECK (tool_calls_used <= max_tool_calls),
    -- A store-scoped role with no store is refused at the boundary in
    -- readonly_sql.visible_stores and retrieve.store_scope_for. This is the
    -- same refusal one layer down, so a run inserted by any other path cannot
    -- smuggle in an unscoped clerk.
    CONSTRAINT agent_runs_scoped_role_has_store CHECK (
        role IN ('manager', 'owner') OR store_id IS NOT NULL
    )
);

CREATE INDEX agent_runs_claimable ON agent_runs (status, created_at)
    WHERE status = 'queued';

COMMENT ON TABLE agent_runs IS
    'One agent invocation. The agent is stateless and this row is the source of '
    'truth (ADR-0003), so a run survives a restart because nothing about it was '
    'held in memory.';
COMMENT ON COLUMN agent_runs.max_tool_calls IS
    'CLAUDE.md rule 3 — the loop caps at ~6 tool calls. Stored per run so a '
    'later config change cannot retroactively make an old run look compliant.';
COMMENT ON COLUMN agent_runs.store_id IS
    'The scope this run acts within. NULL only for manager/owner, enforced by '
    'agent_runs_scoped_role_has_store — rule 5, one layer below the API.';
COMMENT ON COLUMN agent_runs.claimed_by IS
    'The worker holding it. Claimed with SELECT ... FOR UPDATE SKIP LOCKED so '
    'two workers cannot take the same run; a stale claim is reclaimable.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Proposals — the thing a human approves
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE proposed_actions (
    proposed_action_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id    int         NOT NULL REFERENCES agent_runs (agent_run_id),
    tool            text        NOT NULL,
    args            jsonb       NOT NULL,

    -- The card shows these. They are columns rather than prose in `args`
    -- because DESIGN-TOKENS puts them on the face of the card — "Why this
    -- order", "Checked against" — and a card that showed only an amount and an
    -- Approve button would be asking for a signature on an argument it hid.
    reasoning       text        NOT NULL,
    inputs_used     jsonb       NOT NULL,

    status          text        NOT NULL DEFAULT 'pending',
    expires_at      timestamptz NOT NULL,
    approved_by     text        NULL,
    approved_at     timestamptz NULL,
    executed_at     timestamptz NULL,
    -- Why a proposal refused to fire, in the words shown to the approver.
    -- Distinct from agent_runs.error: this is the guardrail working, not a
    -- fault, and merging them would make a successful refusal look like a bug.
    refusal         text        NULL,

    estimated_total numeric(12,2) NULL,
    spending_cap    numeric(12,2) NULL,

    created_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT proposed_actions_status_known CHECK (
        status IN ('pending', 'approved', 'executed', 'rejected', 'expired',
                   'refused')
    ),
    CONSTRAINT proposed_actions_expiry_after_creation
        CHECK (expires_at > created_at),
    -- Approval is a person and a time together or neither. A row approved by
    -- nobody at a timestamp, or by somebody at no time, is an audit trail with
    -- a hole in it.
    CONSTRAINT proposed_actions_approval_is_whole CHECK (
        (approved_by IS NULL) = (approved_at IS NULL)
    ),
    -- Nothing executes without having been approved first. The workflow's one
    -- irreversible step, so it is a constraint rather than a convention.
    CONSTRAINT proposed_actions_execution_requires_approval CHECK (
        executed_at IS NULL OR approved_at IS NOT NULL
    ),
    CONSTRAINT proposed_actions_within_cap CHECK (
        spending_cap IS NULL OR estimated_total IS NULL
        OR estimated_total <= spending_cap
    )
);

CREATE INDEX proposed_actions_queue
    ON proposed_actions (status, expires_at)
    WHERE status = 'pending';
CREATE INDEX proposed_actions_by_run ON proposed_actions (agent_run_id);

COMMENT ON TABLE proposed_actions IS
    'A drafted action awaiting a human. The agent drafts; it does not place. '
    'Expiry, the spending cap and the recorded inputs are what make '
    're-validation at execution time possible rather than aspirational.';
COMMENT ON COLUMN proposed_actions.inputs_used IS
    'The facts this proposal was drafted against — prices, stock, terms, each '
    'with the value read and when. Re-validation compares these to the world at '
    'execution time, so a proposal drafted against a price that has since moved '
    'refuses to fire. Without this column that promise cannot be kept.';
COMMENT ON COLUMN proposed_actions.reasoning IS
    'Why the agent drafted this, in prose, shown on the approval card. '
    'CONVENTIONS.md: the evidence is the design.';
COMMENT ON COLUMN proposed_actions.refusal IS
    'Why it declined to execute — stale input, expiry, cap. The guardrail '
    'working, NOT a fault, which is why it is not merged with agent_runs.error.';
COMMENT ON COLUMN proposed_actions.expires_at IS
    'A column, not a timer. Expiry survives a restart because it was never held '
    'in a process.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Audit — append-only, and the log falls out of the state rather than beside it
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE agent_events (
    agent_event_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id    int         NOT NULL REFERENCES agent_runs (agent_run_id),
    proposed_action_id int      NULL REFERENCES proposed_actions (proposed_action_id),
    kind            text        NOT NULL,
    detail          jsonb       NOT NULL DEFAULT '{}'::jsonb,
    -- Who caused it, when a person did. NULL means the agent or the worker.
    actor           text        NULL,
    occurred_at     timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT agent_events_kind_known CHECK (
        kind IN ('run_queued', 'run_claimed', 'tool_called', 'proposal_drafted',
                 'approved', 'rejected', 'executed', 'expired', 'refused',
                 'run_finished', 'run_failed')
    )
);

CREATE INDEX agent_events_by_run ON agent_events (agent_run_id, occurred_at);

COMMENT ON TABLE agent_events IS
    'Append-only audit. Every state change goes through here, so "what '
    'happened" is a query rather than a reconstruction (ADR-0003, reason 3). '
    'Never updated and never deleted — a log you can edit is not a log.';
COMMENT ON COLUMN agent_events.actor IS
    'The person who caused this event, or NULL for the agent and the worker. '
    'ADR-0002: the agent reports patterns, never people — the approver is the '
    'one identity this workflow is legitimately about.';

-- ─────────────────────────────────────────────────────────────────────────────
-- Grants
--
-- pos_app reads and writes. pos_readonly gets SELECT so the approval queue and
-- the audit log are readable by the same role that answers questions — but NOT
-- INSERT or UPDATE anywhere here: approving is a write, and the role that
-- generated SQL runs under must never be able to approve anything.
-- ─────────────────────────────────────────────────────────────────────────────

GRANT SELECT, INSERT, UPDATE ON agent_runs, proposed_actions TO pos_app;
GRANT SELECT, INSERT ON agent_events TO pos_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO pos_app;
GRANT SELECT ON agent_runs, proposed_actions, agent_events TO pos_readonly;

COMMIT;
